apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - namespace.yaml
  - configmaps-secrets.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - mongodb-deployment.yaml
  - auth-service-deployment.yaml
  - deployment-service-deployment.yaml
  - frontend-service-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: paas-platform
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/managed-by: kustomize

images:
  - name: paas-platform/auth-service
    newTag: latest
  - name: paas-platform/deployment-service
    newTag: latest
  - name: paas-platform/frontend-service
    newTag: latest
