apiVersion: v1
kind: Service
metadata:
  name: otel-gateway-metrics
  namespace: otelagent
spec:
  selector:
    app.kubernetes.io/name: opentelemetry-collector
  ports:
    - name: prometheus-metrics
      port: 8888
      targetPort: 8888
      protocol: TCP
