{{- if and .Values.enableNamespaces .Values.namespaces.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.paas }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.core }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.otelGateway }}
{{- end }}

